/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import model.Cart;
import model.Item;
import model.Inventory;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.CarePackage;
/**
 *
 * @author Sonny
 */
public class DonorGui extends javax.swing.JFrame {
    private Inventory inventory;
    private Cart cart;
    private String itemToCheck = new String();

    /**
     * Creates new form DonorGui
     */
    public DonorGui() {
        initComponents();
        inventory = new Inventory();
        inventory.deserializeInventory();
        cart = new Cart();
        System.out.println(inventory);
        ((DefaultListModel)categoryList.getModel()).addElement("Packages");
        ((DefaultListModel)categoryList.getModel()).addElement("Needed Items");
        ((DefaultListModel)categoryList.getModel()).addElement("Food");
        ((DefaultListModel)categoryList.getModel()).addElement("Clothing");
        ((DefaultListModel)categoryList.getModel()).addElement("Furniture");
        ((DefaultListModel)categoryList.getModel()).addElement("Other");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        packagesPopUp = new javax.swing.JDialog();
        packagesScrollPane = new javax.swing.JScrollPane();
        packagesTextArea = new javax.swing.JTextArea();
        categoryPane = new javax.swing.JScrollPane();
        categoryList =  new javax.swing.JList<String>((new DefaultListModel<String>()));
        cartPane = new javax.swing.JScrollPane();
        cartList =  new javax.swing.JList<String>((new DefaultListModel<String>()));
        submitButton = new javax.swing.JButton();
        categoriesLabel = new javax.swing.JLabel();
        itemsLabel = new javax.swing.JLabel();
        cartLabel = new javax.swing.JLabel();
        itemsPane = new javax.swing.JScrollPane();
        categoryItems =  new javax.swing.JList<String>((new DefaultListModel<String>()));
        removeButton = new javax.swing.JButton();
        quantityAddButton = new javax.swing.JButton();
        quantityTextField = new javax.swing.JTextField();

        packagesPopUp.setPreferredSize(new java.awt.Dimension(1000, 800));
        packagesPopUp.setResizable(false);
        packagesPopUp.setSize(new java.awt.Dimension(500, 700));
        packagesPopUp.setType(java.awt.Window.Type.POPUP);

        packagesTextArea.setEditable(false);
        packagesTextArea.setColumns(20);
        packagesTextArea.setRows(5);
        packagesScrollPane.setViewportView(packagesTextArea);

        javax.swing.GroupLayout packagesPopUpLayout = new javax.swing.GroupLayout(packagesPopUp.getContentPane());
        packagesPopUp.getContentPane().setLayout(packagesPopUpLayout);
        packagesPopUpLayout.setHorizontalGroup(
            packagesPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(packagesPopUpLayout.createSequentialGroup()
                .addComponent(packagesScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                .addContainerGap())
        );
        packagesPopUpLayout.setVerticalGroup(
            packagesPopUpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(packagesScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(java.awt.Color.darkGray);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        categoryList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        categoryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                categoryListValueChanged(evt);
            }
        });
        categoryPane.setViewportView(categoryList);

        cartList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                cartListValueChanged(evt);
            }
        });
        cartPane.setViewportView(cartList);

        submitButton.setForeground(new java.awt.Color(51, 0, 51));
        submitButton.setText("Submit Cart");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });

        categoriesLabel.setText("Categories");

        itemsLabel.setText("Items");

        cartLabel.setText("Cart");

        categoryItems.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                categoryItemsValueChanged(evt);
            }
        });
        itemsPane.setViewportView(categoryItems);

        removeButton.setText("Remove");

        quantityAddButton.setText("Add");
        quantityAddButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quantityAddButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(categoriesLabel)
                .addGap(235, 235, 235)
                .addComponent(itemsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cartLabel)
                .addGap(305, 305, 305))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(categoryPane, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(itemsPane, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(quantityAddButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addComponent(cartPane, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(removeButton)
                .addGap(32, 32, 32))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(submitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(categoriesLabel)
                    .addComponent(itemsLabel)
                    .addComponent(cartLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(cartPane)
                        .addComponent(categoryPane)
                        .addComponent(itemsPane, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE))
                    .addComponent(removeButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(quantityAddButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(40, 40, 40))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_categoryListValueChanged
        if(!evt.getValueIsAdjusting()){
            String s = categoryList.getSelectedValue();
            System.out.println(s);
            if(s.equals("Needed Items")){
                ArrayList<Item> items = inventory.getNeeded();
                ((DefaultListModel)categoryItems.getModel()).clear();
                for(int i = 0;i < items.size();i++){
                    ((DefaultListModel)categoryItems.getModel()).addElement(items.get(i).getItemName());
                }
            }
            else if(s.equals("Packages")){
                String packageInfo = new String();
                ArrayList<CarePackage> packageList = inventory.getPackageList();
                for(int i = 0; i < packageList.size();i++){
                    packageInfo += packageList.get(i);
                }
                packagesTextArea.setText("Package List: \n\n" + packageInfo);
                packagesPopUp.setVisible(true);
            }
            else{
                ArrayList<Item> items = inventory.getItemsOfType(s);
               ((DefaultListModel)categoryItems.getModel()).clear();
                for(int i = 0;i < items.size();i++){
                    ((DefaultListModel)categoryItems.getModel()).addElement(items.get(i).getItemName());
                }
            }
        }
        System.out.println(inventory);
    }//GEN-LAST:event_categoryListValueChanged

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
        inventory.addCart(cart);
        inventory.serializeInventory();
        System.exit(0);
    }//GEN-LAST:event_submitButtonActionPerformed

    private void categoryItemsValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_categoryItemsValueChanged
        if(!evt.getValueIsAdjusting() && categoryItems.getSelectedValue() != null){
            itemToCheck = categoryItems.getSelectedValue();
            System.out.println(inventory);
        }
    }//GEN-LAST:event_categoryItemsValueChanged

    private void cartListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_cartListValueChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cartListValueChanged

    private void quantityAddButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quantityAddButtonMouseClicked
        if(quantityTextField.getText() != null && !itemToCheck.equals("") && itemToCheck != null){
            String quantity = quantityTextField.getText();
            int quant = 0;
            try {
              quant = Integer.parseInt(quantity);
            } 
            catch (NumberFormatException e) {
                System.out.println("Invalid Input");
            }
            System.out.println(quant);
            if(quant > 0 ){
                if(cart.itemExists(itemToCheck)){
                     cart.getItem(itemToCheck).setQuantity(cart.getItem(itemToCheck).getQuantity() + quant);
                     setCartList();
                }
                else{
                    cart.addItem(new Item(itemToCheck, inventory.getItem(itemToCheck).getItemType(),
                                 quant, 0, inventory.getItem(itemToCheck).getValue()));
                    setCartList();
                }
            }
        }
    }//GEN-LAST:event_quantityAddButtonMouseClicked

    private void setCartList(){
         ((DefaultListModel)cartList.getModel()).clear();
         ArrayList<Item> items = cart.getItems();
         for(int i = 0;i < items.size();i++){
              ((DefaultListModel)cartList.getModel()).addElement("<html>" +items.get(i).getItemName() +
                "<br>Quantity: " + items.get(i).getQuantity() + "</html>");
            }
         }

            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DonorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DonorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DonorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DonorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DonorGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cartLabel;
    private javax.swing.JList<String> cartList;
    private javax.swing.JScrollPane cartPane;
    private javax.swing.JLabel categoriesLabel;
    private javax.swing.JList<String> categoryItems;
    private javax.swing.JList<String> categoryList;
    private javax.swing.JScrollPane categoryPane;
    private javax.swing.JLabel itemsLabel;
    private javax.swing.JScrollPane itemsPane;
    private javax.swing.JDialog packagesPopUp;
    private javax.swing.JScrollPane packagesScrollPane;
    private javax.swing.JTextArea packagesTextArea;
    private javax.swing.JButton quantityAddButton;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JButton removeButton;
    private javax.swing.JButton submitButton;
    // End of variables declaration//GEN-END:variables
}
